name: Build + Release Wheels

on:
  workflow_dispatch:
    inputs:
      llvm_version:
        description: "LLVM version to build"
        required: false
        default: ""
      wheel_version:
        description: "Version of the wheel packaging (appended to LLVM version)"
        required: false
        default: "0"
      deploy_to_testpypi:
        description: "Whether the build should be deployed to test.pypi.org instead regular PyPI"
        required: true
        default: false

jobs:
  build-wheels:
    name: Build wheels on ${{ matrix.os }} (arch=${{ matrix.arch }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            arch: "x86_64"
            skip: "*manylinux*"
          - os: ubuntu-24.04
            arch: "x86_64"
            skip: "*musllinux*"
          - os: windows-2022
            arch: "AMD64"
            skip: 
          - os: macos-13
            arch: "x86_64"
            skip: 
          - os: macos-14
            arch: "arm64"
            skip: 

    steps:
    - uses: actions/checkout@v4
    
    - name: Support long paths
      if: runner.os == 'Windows'
      run: git config --system core.longpaths true

    - name: Export macOS SDKROOT
      if: runner.os == 'macOS'
      run: echo SDKROOT=$(xcrun --sdk macosx --show-sdk-path) >> $GITHUB_ENV

    - name: Override LLVM version (${{ github.event.inputs.llvm_version }})
      if: github.event.inputs.llvm_version
      run: |
        echo "set(CLANGD_VERSION ${{ github.event.inputs.llvm_version }})" > clangd_version.cmake
        echo "set(CLANGD_WHEEL_VERSION ${{ github.event.inputs.wheel_version }})" >> clangd_version.cmake

    - uses: actions/setup-python@v5
      with:
        python-version: 3.8
      # the pre-installed python 3.8 isn't native and cannot produce ARM64 wheels
      # see also https://github.com/pypa/cibuildwheel/pull/1871
      if: runner.os == 'macOS' && runner.arch == 'arm64'

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.22.0
      env:
        CIBW_ARCHS: "${{ matrix.arch }}"
        CIBW_BEFORE_TEST:  rm -rf {package}/clangd
        CIBW_TEST_SKIP: "*linux*"
        # always skip PyPY builds + what's defined in the matrix
        CIBW_SKIP: "pp* ${{matrix.skip}}"
    # clangd simply does not want to cooperate with the github linux image
    - name: Test Linux Wheel
      if: runner.os == 'Linux' && matrix.arch == 'x86_64'
      run: |
        if [[ "${{matrix.skip}}" == "*manylinux*" ]] ; then
          docker build --build-arg BASEOS=alpine3.16 --build-arg PLATFORM=musllinux -f .github/workflows/Dockerfile .
        else
          docker build --build-arg BASEOS=slim-bullseye --build-arg PLATFORM=manylinux -f .github/workflows/Dockerfile .        
        fi
    - name: Set artifact name
      id: set_artifact_name
      shell: bash -l {0}
      run: |
        VALUE="archive_wheels_${{ matrix.os }}_${{ matrix.arch }}_${{ matrix.skip }}"
        VALUE="${VALUE//\*/}"
        echo "value=${VALUE}" >> ${GITHUB_OUTPUT}
    - uses: actions/upload-artifact@v4
      with:
        path: ./wheelhouse/*.whl
        name: ${{ steps.set_artifact_name.outputs.value }}

  build-sdist:
    name: Build source distribution
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Override LLVM version (${{ github.event.inputs.llvm_version }})
        if: github.event.inputs.llvm_version
        run: |
          echo "set(CLANGD_VERSION ${{ github.event.inputs.llvm_version }})" > clangd_version.cmake
          echo "set(CLANGD_WHEEL_VERSION ${{ github.event.inputs.wheel_version }})" >> clangd_version.cmake
 
      - name: Build SDist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          path: dist/*.tar.gz
          name: archive_sdist
  
  test-sdist:
    name: Test build from source distribution
    needs: [build-sdist]
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: '3.9'

      - uses: actions/download-artifact@v4
        with:
          name: archive_sdist
          path: sdist

      - name: Install from SDist
        run: |
          # make sure the test will not pick this up  
          rm -r clangd
          pip install sdist/*.tar.gz

      - name: Install test requirements
        run:
          python -m pip install -r requirements-dev.txt

      - name: Run test suite
        run:
          python -m pytest

  upload_pypi:
    name: Upload to PyPI
    needs: [build-wheels, build-sdist, test-sdist]
    runs-on: ubuntu-24.04
    permissions:
      id-token: write    
    if: github.repository_owner == 'jmpfar'

    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: archive*
          path: dist
          merge-multiple: true

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.3
        if: github.event.inputs.deploy_to_testpypi == 'false'

      - name: Upload to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.12.3
        if: github.event.inputs.deploy_to_testpypi == 'true'
        with:
          repository_url: https://test.pypi.org/legacy/
